version: '3.8'

services:
  loan-calculator:
    build:
      context: .
      dockerfile: Dockerfile
    image: loan-calculator-app:latest
    container_name: loan-calculator-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - loan-net
    restart: always

networks:
  loan-net:
    driver: bridge